**Learning Objectives**

After reading, you should be able to:

1. Understand the difference between one-, two- and n-dimensional arrays in NumPy;

2. Understand how to apply some linear algebra operations to n-dimensional arrays without using for-loops;

3. Understand axis and shape properties for n-dimensional arrays.

In [1]:
import numpy as np

# The Basics

Numpy mains obbject is the homgenpous multi-dimensional array. It is a table of elements of all the same type indexed by a tuple of non-negative integers. In Numpy dimensions are called `axes`.



In [4]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

**ndarray.ndim** :-

The number of axes (dimensions) of the array.

In [5]:
#We can get shape of array using 
a.shape

(3, 5)

**ndarray.shape** :- 

The dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, `shape` will be `(n,m)`. The length of the `shape` tuple is therefore the number of axes, `ndim`.

In [7]:
a.size

15

**ndarray.size**:-

The total number of elements of the array. This is equal to the product of the elements of shape.

In [8]:
a.dtype.name

'int64'

**ndarray.dtype**:-

An object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

In [9]:
a.itemsize

8

**ndarray.itemsize**

The size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.



In [10]:
type(a)

numpy.ndarray

# Array Creation

There are Serveral ways to create arrays:

In [13]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [14]:
b = np.array([1.2,3.5,5.1])
b

array([1.2, 3.5, 5.1])

In [16]:
#a = np.array(1,2,3,4) #Wrong

`array` transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [17]:
b = np.array([(1.5,2,4),(4,5,6)])
b

array([[1.5, 2. , 4. ],
       [4. , 5. , 6. ]])

The type of the array can also be explicitly specified at creation time:


In [19]:
c = np.array([[1,2],[3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [20]:
# Zero Array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
#Ones Array
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [23]:
#Empty: Creates Random Array
np.empty((2,3))

array([[1.5, 2. , 4. ],
       [4. , 5. , 6. ]])

To create sequences of numbers, NumPy provides the `arange` function which is analogous to the Python built-in `range`, but returns an array.

In [25]:
np.arange(10,40,5)

array([10, 15, 20, 25, 30, 35])

In [26]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

When `arange` is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. 
For this reason, it is usually better to use the function `linspace`  that receives as an argument the number of elements that we want, instead of the step:

In [28]:
from numpy import pi
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [30]:
x = np.linspace(0,2*pi, 100)
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -